// Generated by https://quicktype.io

class NoticiaModel {
  String? author;
  String? title;
  String? description;
  String? url;
  String? urlToImage;
  String? publishedAt;
  String? content;

  NoticiaModel({
    this.author,
    this.title,
    this.description,
    this.url,
    this.urlToImage,
    this.publishedAt,
    this.content,
  });

  factory NoticiaModel.fromMap(Map<String, dynamic> map) {
    return NoticiaModel(
        author: map['author'],
        title: map['title'],
        description: map['description'],
        url: map['url'],
        urlToImage: map['urlToImage'],
        publishedAt: map['image'],
        content: map['content']);
  }
}
